<? /* vsp stats processor, copyright 2004-2005, myrddin8 AT gmail DOT com (a924cb279be8cb6089387d402288c9f2) */
class VSPParserCOD { var $V93da65a9; var $V21d8a920; var $Vae2aeb93; var $Va2bbabfe; var $V6d2b5d2c;
 var $V42dfa3a4; var $Vc3ecd549; var $V9693e947; var $Vdafa753c; var $V50dffd37; var $Vd6d33a32;
var $logdata; var $Va733fe6b; var $Vb3b1075a; function VSPParserCOD($Ve0d85fdc,&$V4f00ff2f,&$V495c39bf)
 { define("C7e731e80",1024); $this->Fcda1c5ae($Ve0d85fdc); $this->V21d8a920= $V4f00ff2f; $this->Vae2aeb93= $V495c39bf;
 $this->V6d2b5d2c= array(); $this->V42dfa3a4= array(); $this->Va2bbabfe= array(); $this->logdata=array();
 $this->Vdafa753c= false; $this->V42dfa3a4['char_trans']=array( "^^0" => "`#000000", "^1" => "`#FF0000",
 "^2" => "`#00FF00", "^3" => "`#FFFF00", "^4" => "`#4444FF", "^5" => "`#00FFFF", "^6" => "`#FF00FF",
 "^7" => "`#FFFFFF", "^8" => "`#777777", "^9" => "`#777777", ); $this->V42dfa3a4['hit_location']['none']="locnone";
$this->V42dfa3a4['hit_location']['torso_lower']="locstomach"; $this->V42dfa3a4['hit_location']['torso_upper']="locchest";
$this->V42dfa3a4['hit_location']['right_foot']="locleg-right(foot)"; $this->V42dfa3a4['hit_location']['left_foot']="locleg-left(foot)";
$this->V42dfa3a4['hit_location']['right_hand']="locarm-right(hand)"; $this->V42dfa3a4['hit_location']['left_hand']="locarm-left(hand)";
$this->V42dfa3a4['hit_location']['right_arm_upper']="locarm-right(upper)"; $this->V42dfa3a4['hit_location']['left_arm_upper']="locarm-left(upper)";
$this->V42dfa3a4['hit_location']['right_arm_lower']="locarm-right(lower)"; $this->V42dfa3a4['hit_location']['left_arm_lower']="locarm-left(lower)";
$this->V42dfa3a4['hit_location']['right_leg_upper']="locleg-right(upper)"; $this->V42dfa3a4['hit_location']['left_leg_upper']="locleg-left(upper)";
$this->V42dfa3a4['hit_location']['right_leg_lower']="locleg-right(lower)"; $this->V42dfa3a4['hit_location']['left_leg_lower']="locleg-left(lower)";
$this->V42dfa3a4['hit_location']['head']="lochead"; $this->V42dfa3a4['hit_location']['neck']="locneck";
 $this->V42dfa3a4['weapon_name']['search'] =array( "/MOD_/" ,"/.*CRUSH_JEEP.*/" ,"/.*CRUSH_TANK.*/" 
 ,"/.*MELEE.*/" ,"/_duck/" ,"/_prone/" ,"/_semi/" ,"/_silenced/" ,"/_slow/" ,"/_stand/" ,"/_EXPLOSIVE/"
 ,"/_GRENADE/" ,"/_HEAD_SHOT$/" ,"/_PISTOL_BULLET/" ,"/_PROJECTILE/" ,"/_RIFLE_BULLET/" ,"/_SPLASH/"
 ); $this->V42dfa3a4['weapon_name']['replace']=array( "" ,"CRUSH_JEEP" ,"CRUSH_TANK" ,"MELEE" );
 } function Fcda1c5ae($Ve0d85fdc) { $this->V93da65a9['savestate']=0; $this->V93da65a9['gametype']="";
$this->V93da65a9['backuppath']=""; $this->V93da65a9['trackID']="playerName"; if (is_array($Ve0d85fdc))
 { foreach($Ve0d85fdc as $Ve7cb9038 => $Va36fd2a1) { $this->V93da65a9[$Ve7cb9038] = $Va36fd2a1; }
} if ($this->V93da65a9['backuppath']) { $this->V93da65a9['backuppath']=F9578dd1f($this->V93da65a9['backuppath']);
} echo "[parser options]: "; print_r($this->V93da65a9); } function F713be45c() { unset($this->Va2bbabfe);
$this->Va2bbabfe= array(); unset($this->V6d2b5d2c); $this->V6d2b5d2c= array(); $this->V9693e947['month']=12;
$this->V9693e947['date']=28; $this->V9693e947['year']=1971; $this->V9693e947['hour']=23; $this->V9693e947['min']=59;
$this->V9693e947['sec']=59; } function F5c0b129c() { $this->logdata["last_shutdown_end_position"]=ftell($this->V50dffd37); 
 $V9a52fe40=fseek ($this->V50dffd37, -C7e731e80, SEEK_CUR); if ($V9a52fe40==0) { $this->logdata['last_shutdown_hash']=md5(fread($this->V50dffd37, C7e731e80));
} else { $V284073b9=ftell($this->V50dffd37); fseek ($this->V50dffd37, 0); $this->logdata['last_shutdown_hash']=md5(fread($this->V50dffd37, $V284073b9)); 
 } $V3b2eb2c1 = fopen('./logdata/savestate_'.Fff47f8ac($this->Vd6d33a32).'.inc.php',"wb"); fwrite($V3b2eb2c1,"<?/"."* DO NOT EDIT THIS FILE! */\n");
fwrite($V3b2eb2c1,"\$this->logdata['last_shutdown_hash']='{$this->logdata['last_shutdown_hash']}';\n");
fwrite($V3b2eb2c1,"\$this->logdata['last_shutdown_end_position']={$this->logdata['last_shutdown_end_position']};\n");
fwrite($V3b2eb2c1,"?>"); fclose($V3b2eb2c1); } function Fb96636b2() { echo "Verifying savestate\n";
$V8774de0e=fopen($this->Vd6d33a32,"rb"); $V2843c763=fseek($V8774de0e,$this->logdata['last_shutdown_end_position']);
 if ($V2843c763==0) { $V9a52fe40=fseek ($V8774de0e, -C7e731e80, SEEK_CUR); if ($V9a52fe40==0) { 
 $Vb9cc7f4b=fread($V8774de0e, C7e731e80); } else { $V284073b9=ftell($V8774de0e); fseek ($V8774de0e, 0);
$Vb9cc7f4b=fread($V8774de0e, $V284073b9); } if (strcmp(md5($Vb9cc7f4b),$this->logdata['last_shutdown_hash'])==0)
 { echo " - Hash matched, resuming parsing from previous saved location in log file\n"; fseek($this->V50dffd37,$this->logdata['last_shutdown_end_position']);
} else { echo " - Hash did not match, assuming new log file\n"; fseek($this->V50dffd37,0); } } else
 { echo " - Seek to prior location failed, assuming new log file\n"; fseek($this->V50dffd37,0); }
 fclose($V8774de0e); } function F1417ca90($Vdbe56eaf) { $this->Vd6d33a32=realpath($Vdbe56eaf); 
 if (!file_exists($this->Vd6d33a32)) { F03c2b497("error: log file \"{$Vdbe56eaf}\" does not exist");
} $this->F713be45c(); if ($this->V93da65a9['savestate']==1) { echo "savestate 1 processing enabled\n";
@include_once('./logdata/savestate_'.Fff47f8ac($this->Vd6d33a32).'.inc.php'); $this->V50dffd37= fopen($this->Vd6d33a32,"rb");
 if (!empty($this->logdata)) { $this->Fb96636b2(); } } else { $this->V50dffd37= fopen($this->Vd6d33a32,"rb");
} if (!$this->V50dffd37) { Fb7d30ee1("error: {this->logfile} could not be opened"); return; } $this->V42dfa3a4['logfile_size']=filesize($this->Vd6d33a32); 
 while(!feof($this->V50dffd37)) { $this->Va733fe6b=ftell($this->V50dffd37); $V6438c669 = fgets($this->V50dffd37, cBIG_STRING_LENGTH); 
 $V6438c669=rtrim($V6438c669,"\r\n"); $this->F20dd322a($V6438c669); } fclose($this->V50dffd37); 
 } function F7212cda9($V341be97d) { $Vfc9b3a06=preg_replace("/\\^[1-9]/","",$V341be97d); $Vfc9b3a06=preg_replace("/\\^\\^0/","",$Vfc9b3a06);
return $Vfc9b3a06; } function Fa3f5d48d($V341be97d) { $Vf8f0c0d8="`#FFFFFF"; $Vf8f0c0d8.= strtr($V341be97d, $this->V42dfa3a4['char_trans']);
return $Vf8f0c0d8; } function Fe846ce3f($Vb0aae2e8) { foreach($this->Va2bbabfe as $V74aaef3b => $V9ba96d33)
 { if (!strcmp($this->Va2bbabfe[$V74aaef3b]['id'],$Vb0aae2e8)) { return $V74aaef3b; } } return "";
} function F381a6ffc($V3b043eba) { foreach($this->Va2bbabfe as $V74aaef3b => $V9ba96d33) { if (!strcmp($this->Va2bbabfe[$V74aaef3b]['name'],$V3b043eba))
 { return $V74aaef3b; } } return ""; } function Ffa84691e() { if (preg_match("/^(\d+)[\\:\\.](\d+)[\\:\\.](\d+)/", $this->Vc3ecd549, $Vb74df323))
 { $V110decc3['hour']=$Vb74df323[1]; $V110decc3['min'] =$Vb74df323[2]; $V110decc3['sec'] =$Vb74df323[3];
return date ("Y-m-d H:i:s", adodb_mktime ($V110decc3['hour'],$V110decc3['min'],$V110decc3['sec'],$this->V9693e947['month'],$this->V9693e947['date'],$this->V9693e947['year']));
} else if (preg_match("/^(\d+):(\d+)/", $this->Vc3ecd549, $Vb74df323)) { $V110decc3['min']=$Vb74df323[1];
$V110decc3['sec']=$Vb74df323[2]; return date ("Y-m-d H:i:s", adodb_mktime ($this->V9693e947['hour'],$this->V9693e947['min']+$V110decc3['min'],$this->V9693e947['sec']+$V110decc3['sec'],$this->V9693e947['month'],$this->V9693e947['date'],$this->V9693e947['year']));
} else if (preg_match("/^(\d+).(\d+)/", $this->Vc3ecd549, $Vb74df323)) { $V110decc3['min']=0; $V110decc3['sec']=$Vb74df323[1]; 
 return date ("Y-m-d H:i:s", adodb_mktime ($this->V9693e947['hour'],$this->V9693e947['min']+$V110decc3['min'],$this->V9693e947['sec']+$V110decc3['sec'],$this->V9693e947['month'],$this->V9693e947['date'],$this->V9693e947['year']));
} } function F7939839b(&$V6438c669) { if (!preg_match("/^InitGame: (.*)/", $V6438c669, $Vb74df323))
 return false; if ($this->Vdafa753c) { Fb7d30ee1("corrupt game (no Shutdown after Init), ignored\n");
Fb7d30ee1("{$this->Vc3ecd549} $V6438c669\n"); $this->Vae2aeb93->Fc3b570a7(); $this->Vae2aeb93->F242ca9da();
 } $this->Vdafa753c= true; $this->Vb3b1075a=$this->Va733fe6b; $this->F713be45c(); $Vf81b2562=$Vb74df323[1];
while (preg_match("/^\\\(.+)\\\(.+)\\\/U", $Vf81b2562, $Va9ddcf51) || preg_match("/^\\\(.+)\\\(.+)/", $Vf81b2562, $Va9ddcf51))
 { $Vccedf499=$Va9ddcf51[1]; $Vcc14d460=$Va9ddcf51[2]; $Ve37f0136[$Vccedf499]=$Vcc14d460; $Vf81b2562=substr($Vf81b2562,strlen($Vccedf499)+strlen($Vcc14d460)+2);
if (!strcmp($Vccedf499,"gamestartup")) { if (preg_match("/^(\d+)[-\/](\d+)[-\/](\d+) +(\d+)[:-](\d+)[:-](\d+)/", $Vcc14d460, $Vd6fd0924))
 { $this->V9693e947['month']=$Vd6fd0924[1]; $this->V9693e947['date']=$Vd6fd0924[2]; $this->V9693e947['year']=$Vd6fd0924[3];
$this->V9693e947['hour']=$Vd6fd0924[4]; $this->V9693e947['min']=$Vd6fd0924[5]; $this->V9693e947['sec']=$Vd6fd0924[6];
} } } $this->Vae2aeb93->Fd45b6912(); foreach($Ve37f0136 as $V2948dbaa => $V91dfc652) { $this->Vae2aeb93->F6d04475a($V2948dbaa,$V91dfc652);
} $this->Vae2aeb93->F6d04475a("_v_time_start",$this->Ffa84691e()); $this->Vae2aeb93->F6d04475a("_v_map",$Ve37f0136['mapname']);
$this->Vae2aeb93->F6d04475a("_v_game",'cod'); $this->Vae2aeb93->F6d04475a("_v_mod",$Ve37f0136['gamename']);
$this->Vae2aeb93->F6d04475a("_v_game_type",$Ve37f0136['g_gametype']); $this->V42dfa3a4['mod']=$Ve37f0136['gamename'];
$this->V42dfa3a4['gametype']=$Ve37f0136['g_gametype']; $this->F166e2aad(); return true; } function F50a7dad5(&$V6438c669)
 { if (!preg_match("/^Q;(\w+);(\d+);(.*)/", $V6438c669, $Vb74df323)) return false; $V2bfe9d72=$Vb74df323[2];
 if (isset($this->Va2bbabfe[$V2bfe9d72])) { unset($this->Va2bbabfe[$V2bfe9d72]); } return true; } 
 function F302637e2() { $this->Vae2aeb93->Fc3b570a7(); $this->Vae2aeb93->F242ca9da(); $this->Vdafa753c= false;
while(!feof($this->V50dffd37)) { $V6438c669 = fgets($this->V50dffd37, cBIG_STRING_LENGTH); $this->F1ef9b71a($V6438c669);
if (preg_match("/^ShutdownGame:/", $V6438c669)) break; } } function Fad2f8a9d(&$V6438c669) { if (!preg_match("/^J;(\w+);(\d+);(.*)/", $V6438c669, $Vb74df323))
 return false; $V2bfe9d72=$Vb74df323[2]; $Vc1a5f989=$Vb74df323[3]; $V0b5a0d9e=$Vb74df323[1]; $V1963b948=$this->Fa3f5d48d($Vb74df323[3]);
if ($V0b5a0d9e!='0') { if (isset($this->Va2bbabfe[$V2bfe9d72]['guid']) && $this->Va2bbabfe[$V2bfe9d72]['guid']!=$V0b5a0d9e)
 { echo "Player with a diff GUID connected to same slot without a Quit (this shouldn't happen)...\n";
echo "{$this->Vc3ecd549} $V6438c669\n"; echo "force quitting the old player: id=".$this->Va2bbabfe[$V2bfe9d72]['id']."\n";
unset($this->Va2bbabfe[$V2bfe9d72]); } $this->Va2bbabfe[$V2bfe9d72]['guid']=$V0b5a0d9e; } if (isset($this->Va2bbabfe[$V2bfe9d72]['id']) && $this->V93da65a9['trackID']=='playerName' && strcmp($this->Va2bbabfe[$V2bfe9d72]['id'],$Vc1a5f989)!=0)
 { $this->Vae2aeb93->Fec5ab55c("sto",$this->Va2bbabfe[$V2bfe9d72]['id'],"alias",$V1963b948); $this->Vae2aeb93->Fddcbd60f($this->Va2bbabfe[$V2bfe9d72]['id'],$V1963b948);
$this->Vae2aeb93->F95791962($this->Va2bbabfe[$V2bfe9d72]['id'],$Vc1a5f989); $this->Va2bbabfe[$V2bfe9d72]['id']=$Vada01463;
} else if (isset($this->Va2bbabfe[$V2bfe9d72]['id']) && isset($this->Va2bbabfe[$V2bfe9d72]['name']) && strcmp($this->Va2bbabfe[$V2bfe9d72]['name'],$V1963b948)!=0)
 { $this->Vae2aeb93->Fec5ab55c("sto",$this->Va2bbabfe[$V2bfe9d72]['id'],"alias",$V1963b948); $this->Vae2aeb93->Fddcbd60f($this->Va2bbabfe[$V2bfe9d72]['id'],$V1963b948);
} else if ($this->V93da65a9['trackID'] == 'playerName') { $this->Va2bbabfe[$V2bfe9d72]['id']=$Vc1a5f989; 
 } else if ($this->V93da65a9['trackID'] == 'guid' && isset($this->Va2bbabfe[$V2bfe9d72]['guid'])) {
 $this->Va2bbabfe[$V2bfe9d72]['id']=$this->Va2bbabfe[$V2bfe9d72]['guid']; } else if (preg_match("/^ip=(.+)/i",$this->V93da65a9['trackID'],$Vd6fd0924) 
 && isset($this->Va2bbabfe[$V2bfe9d72]['ip']) && preg_match($Vd6fd0924[1],$this->Va2bbabfe[$V2bfe9d72]['ip'],$V793914c9))
 { $this->Va2bbabfe[$V2bfe9d72]['id']=$V793914c9[1]; } else { Fb7d30ee1("\$cfg['parser']['trackID'] is invalid, ignored\n");
Fb7d30ee1("Use \$cfg['parser']['trackID'] = 'playerName'; in your config\n"); Fb7d30ee1("{$this->Vc3ecd549} $V6438c669\n");
$this->F302637e2(); return true; } $this->Va2bbabfe[$V2bfe9d72]['name']=$V1963b948; if (isset($this->Va2bbabfe[$V2bfe9d72]['id']))
 { if (isset($this->Va2bbabfe[$V2bfe9d72]['name'])) { $this->Vae2aeb93->F6aae4907($this->Va2bbabfe[$V2bfe9d72]['id'],$this->Va2bbabfe[$V2bfe9d72]['name']); 
 } if (isset($this->Va2bbabfe[$V2bfe9d72]['team'])) $this->Vae2aeb93->F555c9055($this->Va2bbabfe[$V2bfe9d72]['id'],$this->Va2bbabfe[$V2bfe9d72]['team']);
if (isset($this->Va2bbabfe[$V2bfe9d72]['role'])) $this->Vae2aeb93->Fa3f3cadc($this->Va2bbabfe[$V2bfe9d72]['id'],$this->Va2bbabfe[$V2bfe9d72]['role']);
if (isset($this->Va2bbabfe[$V2bfe9d72]['icon'])) $this->Vae2aeb93->F72d01d3f($this->Va2bbabfe[$V2bfe9d72]['id'],"icon|{$this->Va2bbabfe[$V2bfe9d72]['icon']}",1);
if (isset($this->Va2bbabfe[$V2bfe9d72]['ip'])) $this->Vae2aeb93->Fec5ab55c("sto",$this->Va2bbabfe[$V2bfe9d72]['id'],"ip",$this->Va2bbabfe[$V2bfe9d72]['ip']); 
 if (isset($this->Va2bbabfe[$V2bfe9d72]['guid'])) $this->Vae2aeb93->Fec5ab55c("sto",$this->Va2bbabfe[$V2bfe9d72]['id'],"guid",$this->Va2bbabfe[$V2bfe9d72]['guid']);
} else { } return true; } function F2dbe1582(&$V6438c669) { if (!preg_match("/^D;(\w+);(\d+);(.*);(.*);(\w*);(-?\d+);(.*);(.*);(.*);(\d+);(.*);(.*)/", $V6438c669, $Vb74df323))
 return false; $V0a9eebf6=$Vb74df323[6]; $V7f138675=$Vb74df323[7]; $V6426a622=$Vb74df323[2]; $Vebab7890=$Vb74df323[3];
$Ved7f969f=$Vb74df323[11]; $V2e7bf2ef=preg_replace("/_mp$/","",$Vb74df323[9]) . "_" . $Ved7f969f;
$V2e7bf2ef=rtrim(preg_replace($this->V42dfa3a4['weapon_name']['search'], $this->V42dfa3a4['weapon_name']['replace'],$V2e7bf2ef),"_"); 
 $V8283506e=$Vb74df323[12]; $Vda14a716=$Vb74df323[10]; if ($this->V42dfa3a4['gametype']=='dm' || $this->V42dfa3a4['gametype']=='sdm')
 { $V7f138675=''; $Vebab7890=''; } if ($V0a9eebf6<0) $V0a9eebf6=$V6426a622; $this->Vae2aeb93->F555c9055($this->Va2bbabfe[$V6426a622]['id'],$Vebab7890);
 if ($V0a9eebf6!=$V6426a622) { $this->Vae2aeb93->F555c9055($this->Va2bbabfe[$V0a9eebf6]['id'],$V7f138675);
 $this->Vae2aeb93->F4135e567($this->Va2bbabfe[$V0a9eebf6]['id'], $this->Va2bbabfe[$V0a9eebf6]['id'], "accuracy|{$V2e7bf2ef}_hits",1);
$this->Vae2aeb93->F4135e567($this->Va2bbabfe[$V0a9eebf6]['id'], $this->Va2bbabfe[$V0a9eebf6]['id'], "accuracy|{$V2e7bf2ef}_shots",1);
$this->Vae2aeb93->F4135e567($this->Va2bbabfe[$V0a9eebf6]['id'], $this->Va2bbabfe[$V0a9eebf6]['id'], "accuracy|{$V2e7bf2ef}_".$this->V42dfa3a4['hit_location'][$V8283506e],1);
} if ($Vda14a716>0) { if ($Vda14a716>=1000) $Vda14a716=100; if ($V0a9eebf6!=$V6426a622) $this->Vae2aeb93->F72d01d3f($this->Va2bbabfe[$V0a9eebf6]['id'],"damage given",$Vda14a716);
$this->Vae2aeb93->F72d01d3f($this->Va2bbabfe[$V6426a622]['id'],"damage taken",$Vda14a716); } return true;
 } function F58a1721d(&$V6438c669) { if (!preg_match("/^K;(\w+);(\d+);(.*);(.*);(\w*);(-?\d+);(.*);(.*);(.*);(\d+);(.*);(.*)/", $V6438c669, $Vb74df323))
 return false; $V4b8cff0e=$Vb74df323[6]; $V0c0ebc3b=$Vb74df323[7]; $V6426a622=$Vb74df323[2]; $Vebab7890=$Vb74df323[3];
$Ved7f969f=$Vb74df323[11]; $V2e7bf2ef=preg_replace("/_mp$/","",$Vb74df323[9]) . "_" . $Ved7f969f; $V2e7bf2ef=rtrim(preg_replace($this->V42dfa3a4['weapon_name']['search'], $this->V42dfa3a4['weapon_name']['replace'],$V2e7bf2ef),"_"); 
 $V8283506e=$Vb74df323[12]; $Vda14a716=$Vb74df323[10]; if ($this->V42dfa3a4['gametype']=='dm' || $this->V42dfa3a4['gametype']=='sdm')
 { $V0c0ebc3b=''; $Vebab7890=''; } $V2da111cd=$Vb74df323[4]; $V7edf0aa1=$Vb74df323[8]; if ($V6426a622==$V4b8cff0e && strcmp($V2da111cd,$V7edf0aa1)!=0)
 { $V38efd71c=$this->F381a6ffc($this->Fa3f5d48d($V2da111cd)); if (strlen($V38efd71c)>0) { $V6426a622=$V38efd71c;
} else { echo "Warning: could not fix logging issue in Kill line\n"; echo $V6438c669."\n"; echo "Some stats in current game may be missed\n";
return true; } } if ($V4b8cff0e<0) $V4b8cff0e=$V6426a622; $this->Vae2aeb93->F555c9055($this->Va2bbabfe[$V6426a622]['id'],$Vebab7890);
 if ($V4b8cff0e!=$V6426a622) { $this->Vae2aeb93->F555c9055($this->Va2bbabfe[$V4b8cff0e]['id'],$V0c0ebc3b);
 $this->Vae2aeb93->F4135e567($this->Va2bbabfe[$V4b8cff0e]['id'], $this->Va2bbabfe[$V4b8cff0e]['id'], "accuracy|{$V2e7bf2ef}_hits",1);
$this->Vae2aeb93->F4135e567($this->Va2bbabfe[$V4b8cff0e]['id'], $this->Va2bbabfe[$V4b8cff0e]['id'], "accuracy|{$V2e7bf2ef}_shots",1);
$this->Vae2aeb93->F4135e567($this->Va2bbabfe[$V4b8cff0e]['id'], $this->Va2bbabfe[$V4b8cff0e]['id'], "accuracy|{$V2e7bf2ef}_".$this->V42dfa3a4['hit_location'][$V8283506e],1);
} if ($Vda14a716>0) { if ($Vda14a716>=1000) $Vda14a716=100; if ($V4b8cff0e!=$V6426a622) $this->Vae2aeb93->F72d01d3f($this->Va2bbabfe[$V4b8cff0e]['id'],"damage given",$Vda14a716);
$this->Vae2aeb93->F72d01d3f($this->Va2bbabfe[$V6426a622]['id'],"damage taken",$Vda14a716); } if (isset($this->Va2bbabfe[$V4b8cff0e]['id']) && isset($this->Va2bbabfe[$V6426a622]['id']))
 { $this->Vae2aeb93->Fd65f3244($this->Va2bbabfe[$V4b8cff0e]['id'],$this->Va2bbabfe[$V6426a622]['id'],$V2e7bf2ef);
} return true; } function F238134c5(&$V6438c669) { if (!preg_match("/^A;(\w+);(\d+);(.*);(.*);(.*)/", $V6438c669, $Vb74df323))
 return false; $V2bfe9d72=$Vb74df323[2]; $V2da2c443=$Vb74df323[5]; $Vf894427c=$Vb74df323[3]; $V2da2c443=preg_replace("/^bas_/","BAS|",$V2da2c443);
$V2da2c443=preg_replace("/^ctf_/","CTF|",$V2da2c443); $V2da2c443=preg_replace("/^dom_/","DOM|",$V2da2c443);
$V2da2c443=preg_replace("/^re_/","RE|",$V2da2c443); if ($this->V42dfa3a4['gametype']=='dm' || $this->V42dfa3a4['gametype']=='sdm')
 { $Vf894427c=''; } if (isset($this->Va2bbabfe[$V2bfe9d72]['id'])) { $this->Vae2aeb93->F555c9055($this->Va2bbabfe[$V2bfe9d72]['id'],$Vf894427c);
$this->Vae2aeb93->F72d01d3f($this->Va2bbabfe[$V2bfe9d72]['id'],$V2da2c443,1); } return true; } function Fc943ad61(&$V6438c669)
 { if (!preg_match("/^Weapon;(\w+);(\d+);(.*);(.*)/", $V6438c669, $Vb74df323)) return false; $V2bfe9d72=$Vb74df323[2];
$V2e7bf2ef="weapon|".preg_replace("/_mp$/","",$Vb74df323[4]); if (isset($this->Va2bbabfe[$V2bfe9d72]['id']))
 { $this->Vae2aeb93->F72d01d3f($this->Va2bbabfe[$V2bfe9d72]['id'],$V2e7bf2ef,1); } return true; } 
 function Fa3c3a4ae(&$V6438c669) { if (!preg_match("/^Item;(\w+);(\d+);(.*);(.*)/", $V6438c669, $Vb74df323))
 return false; $V2bfe9d72=$Vb74df323[2]; $V9d0307ba=$Vb74df323[4]; $V9d0307ba=preg_replace("/^ammo_/","ammo|",$V9d0307ba,1);
$V9d0307ba=preg_replace("/^weapon_/","weapon|",$V9d0307ba,1); $V9d0307ba=preg_replace("/^item_/","item|",$V9d0307ba,1); 
 if (isset($this->Va2bbabfe[$V2bfe9d72]['id'])) { $this->Vae2aeb93->F72d01d3f($this->Va2bbabfe[$V2bfe9d72]['id'],$V9d0307ba,1);
} return true; } function F3237fc51(&$V6438c669) { if (!preg_match("/^say;(\w+);(\d+);(.*);.(.*)/", $V6438c669, $Vb74df323))
 return false; $V2bfe9d72=$Vb74df323[2]; $Vaa8af3eb=$Vb74df323[4]; if (isset($this->Va2bbabfe[$V2bfe9d72]))
 { $this->Vae2aeb93->F8405e6ea($this->Va2bbabfe[$V2bfe9d72]['id'],$this->F7212cda9($Vaa8af3eb)); }
return true; } function Fc5aace53(&$V6438c669) { if (!preg_match("/^ShutdownGame:/", $V6438c669, $Vb74df323))
 return false; if ($this->V93da65a9['savestate']==1) { $this->F5c0b129c(); } if (isset($this->V6d2b5d2c['Wins']) && isset($this->V6d2b5d2c['Loss']))
 { arsort($this->V6d2b5d2c['Wins']); arsort($this->V6d2b5d2c['Loss']); $V11f1ad56=each($this->V6d2b5d2c['Wins']);
$V10682a4e =each($this->V6d2b5d2c['Loss']); $this->Vae2aeb93->F89da123b($V11f1ad56['key'],"team|wins",1);
$this->Vae2aeb93->F89da123b($V10682a4e['key'] ,"team|loss",1); if ($V11f1ad56['value']>1) { $this->Vae2aeb93->F89da123b($V11f1ad56['key'],"team|rounds_won",$V11f1ad56['value']);
$this->Vae2aeb93->F89da123b($V10682a4e['key'] ,"team|rounds_won",current($this->V6d2b5d2c['Loss'])); 
 } } $this->Vae2aeb93->Fc3b570a7(); $this->V21d8a920->F43781db5($this->Vae2aeb93->F26dd5333(),$this->Vae2aeb93->F068fac4f());
$this->Vae2aeb93->F242ca9da(); $this->Vdafa753c= false; return true; } function Fcd5b6a5f(&$V6438c669)
 { if (!preg_match("/^W;([^;\n\r]+)/", $V6438c669, $Vb74df323)) return false; $Vf894427c=$Vb74df323[1]; 
 if (!isset($this->V6d2b5d2c['Wins'][$Vf894427c])) $this->V6d2b5d2c['Wins'][$Vf894427c]=0; $this->V6d2b5d2c['Wins'][$Vf894427c]++;
return true; } function F44d600b0(&$V6438c669) { if (!preg_match("/^L;([^;\n\r]+)/", $V6438c669, $Vb74df323))
 return false; $Vf894427c=$Vb74df323[1]; if (!isset($this->V6d2b5d2c['Loss'][$Vf894427c])) $this->V6d2b5d2c['Loss'][$Vf894427c]=0;
$this->V6d2b5d2c['Loss'][$Vf894427c]++; return true; } function F26a565c8(&$V6438c669) { return false;
} function F1ef9b71a(&$V6438c669) { if (preg_match("/^\[(\d+[\\:\\.]\d+[\\:\\.]\d+)\] */", $V6438c669, $Va9ddcf51))
 { $this->Vc3ecd549=$Va9ddcf51[1]; $V6438c669=substr($V6438c669,strlen($Va9ddcf51[0])); return true;
} else if (preg_match("/^(\d+[\\:\\.]\d+[\\:\\.]\d+) */", $V6438c669, $Va9ddcf51)) { $this->Vc3ecd549=$Va9ddcf51[1];
$V6438c669=substr($V6438c669,strlen($Va9ddcf51[0])); return true; } else if (preg_match("/^ *(\d+[\\:\\.]\d+) */", $V6438c669, $Vb74df323))
 { $this->Vc3ecd549=$Vb74df323[1]; $V6438c669=substr($V6438c669,strlen($Vb74df323[0])); return true;
} return false; } function F5541584f(&$V6438c669) { if (!preg_match("/^RestartGame:/", $V6438c669, $Vb74df323))
 return false; while(!feof($this->V50dffd37)) { $V6438c669 = fgets($this->V50dffd37, cBIG_STRING_LENGTH); 
 $this->F1ef9b71a($V6438c669); if (preg_match("/^InitGame:/", $V6438c669)) break; } return true; } 
 function F166e2aad() { if ($this->V42dfa3a4['gametype']=='dm' || $this->V42dfa3a4['gametype']=='sdm') 
 return; $V6205e95b=ftell($this->V50dffd37); while(!feof($this->V50dffd37)) { $Vfcd794a6 = fgets($this->V50dffd37, cBIG_STRING_LENGTH); 
 $this->F1ef9b71a($Vfcd794a6); if (preg_match("/^ShutdownGame:/", $Vfcd794a6)) { break; } else if (preg_match("/^K;(\w+);(\d+);(.+);(.*);(\w*);(-?\d+);(.+);(.*);(.*);(\d+);(.*);(.*)/", $Vfcd794a6, $Vb74df323))
 { $Vebab7890=$Vb74df323[3]; $V0c0ebc3b=$Vb74df323[7]; $V4b8cff0e=$Vb74df323[6]; $this->Vae2aeb93->F52d4d302($Vebab7890);
if ($V4b8cff0e>=0) $this->Vae2aeb93->F52d4d302($V0c0ebc3b); } } fseek($this->V50dffd37,$V6205e95b); 
 } function F20dd322a(&$V6438c669) { $this->F1ef9b71a($V6438c669); if ($this->F7939839b($V6438c669))
 { echo sprintf("(%05.2f%%) ",100.0 * ftell($this->V50dffd37)/$this->V42dfa3a4['logfile_size']); }
else if ($this->Vdafa753c) { if ($this->F26a565c8($V6438c669)) { } else if ($this->F2dbe1582($V6438c669))
 { } else if ($this->F58a1721d($V6438c669)) { } else if ($this->F3237fc51($V6438c669)) { } else if ($this->Fc943ad61($V6438c669))
 { } else if ($this->Fa3c3a4ae($V6438c669)) { } else if ($this->F238134c5($V6438c669)) { } else if ($this->Fad2f8a9d($V6438c669))
 { } else if ($this->F50a7dad5($V6438c669)) { } else if ($this->Fc5aace53($V6438c669)) { } else if ($this->Fcd5b6a5f($V6438c669))
 { } else if ($this->F44d600b0($V6438c669)) { } else if ($this->F5541584f($V6438c669)) { } else
 { } } else { } } } ?>