<? /* vsp stats processor, copyright 2004-2005, myrddin8 AT gmail DOT com (a924cb279be8cb6089387d402288c9f2) */
class VSPParserHL { var $V93da65a9; var $V21d8a920; var $Vae2aeb93; var $Va2bbabfe; var $V6d2b5d2c;
 var $V42dfa3a4; var $V110decc3; var $Vc3ecd549; var $V9693e947; var $Vdafa753c; var $V50dffd37;
 var $Vd6d33a32; var $logdata; function VSPParserHL($Ve0d85fdc,&$V4f00ff2f,&$V495c39bf) { define("C7e731e80",1024);
$this->Fcda1c5ae($Ve0d85fdc); $this->V21d8a920= $V4f00ff2f; $this->Vae2aeb93= $V495c39bf; $this->V6d2b5d2c= array();
$this->V42dfa3a4= array(); $this->Va2bbabfe= array(); $this->Vdafa753c= false; } function Fcda1c5ae($Ve0d85fdc)
 { $this->V93da65a9['savestate']=0; $this->V93da65a9['gametype']=""; $this->V93da65a9['backuppath']="";
$this->V93da65a9['trackID']="playerName"; if (is_array($Ve0d85fdc)) { foreach($Ve0d85fdc as $Vb2145aac => $V3a6d0284)
 { $this->V93da65a9[$Vb2145aac] = $V3a6d0284; } } if ($this->V93da65a9['backuppath']) { $this->V93da65a9['backuppath']=F9578dd1f($this->V93da65a9['backuppath']);
} print_r($this->V93da65a9); } function F713be45c() { unset($this->Va2bbabfe); $this->Va2bbabfe= array();
unset($this->V6d2b5d2c); $this->V6d2b5d2c= array(); $this->V9693e947['month']=12; $this->V9693e947['date']=28;
$this->V9693e947['year']=1971; $this->V9693e947['hour']=23; $this->V9693e947['min']=59; $this->V9693e947['sec']=59;
} function Ff1c5cbd4($Vd6d33a32) { Fb7d30ee1("creating backup..."); $Ve1ee591e=$this->V93da65a9['backuppath'].Fff47f8ac($Vd6d33a32);
 F331c0468($this->V93da65a9['backuppath']); copy($Vd6d33a32, $Ve1ee591e); unlink($Vd6d33a32); Fb7d30ee1("done\n");
} function F5c0b129c() { $V9a52fe40=fseek ($this->V50dffd37, -C7e731e80, SEEK_END); if ($V9a52fe40==0)
 { $Vb9cc7f4b=fread($this->V50dffd37, C7e731e80); } else { fseek ($this->V50dffd37, 0, SEEK_END);
$V284073b9=ftell($this->V50dffd37); fseek ($this->V50dffd37, 0); $Vb9cc7f4b=fread($this->V50dffd37, $V284073b9); 
 } $this->logdata[md5($Vb9cc7f4b)]=''; $V3b2eb2c1 = fopen('./logdata/savestate_'.Fff47f8ac(preg_replace("/[^\\/\\\]+$/","",$this->Vd6d33a32)).'.inc.php',"wb");
fwrite($V3b2eb2c1,"<?/"."* DO NOT EDIT THIS FILE! */\n"); foreach($this->logdata as $V0800fc57=>$V3a6d0284)
 fwrite($V3b2eb2c1,"\$this->logdata['$V0800fc57']='';\n"); fwrite($V3b2eb2c1,"?>"); fclose($V3b2eb2c1); 
 } function F4cca0efe() { echo " - Verifying savestate\n"; $V8774de0e=fopen($this->Vd6d33a32,"rb");
 $V9a52fe40=fseek ($V8774de0e, -C7e731e80, SEEK_END); if ($V9a52fe40==0) { $Vb9cc7f4b=fread($V8774de0e, C7e731e80);
} else { fseek ($V8774de0e, 0, SEEK_END); $V284073b9=ftell($V8774de0e); fseek ($V8774de0e, 0); $Vb9cc7f4b=fread($V8774de0e, $V284073b9); 
 } fclose($V8774de0e); if (isset($this->logdata[md5($Vb9cc7f4b)])) { echo " - Hash matched, log has been processed previousely, ignored\n";
return true; } else { echo " - Hash did not match, assuming new log file\n"; return false; } } 
 function F1417ca90($V36e2287c) { $Vee6da4c2=realpath($V36e2287c); if (!is_dir($Vee6da4c2)) { F03c2b497("error: directory \"$Vee6da4c2\" does not exist. Specify the directory where the log files are.");
} $Vee6da4c2=F9578dd1f($Vee6da4c2); if ($Ve1260894 = opendir($Vee6da4c2) ) { while (false !== ($V8c7dd922 = readdir($Ve1260894))) 
 { if ($V8c7dd922 != "." && $V8c7dd922 != ".." && is_dir($Vee6da4c2.$V8c7dd922)==FALSE) { $V4d63e2b4[]=$Vee6da4c2.$V8c7dd922;
} } closedir($Ve1260894); } if (!isset($V4d63e2b4)) F03c2b497("No logs were found in the directory \"$Vee6da4c2\""); 
 $this->V42dfa3a4['logfile_total']=count($V4d63e2b4); if ($this->V93da65a9['savestate']==1) { echo "savestate 1 processing enabled\n";
@include_once('./logdata/savestate_'.Fff47f8ac($Vee6da4c2).'.inc.php'); } foreach ($V4d63e2b4 as $V7fa3b767 => $Vd6d33a32)
 { print "processing $Vd6d33a32\n"; $this->Vd6d33a32=$Vd6d33a32; $this->F713be45c(); if ($this->V93da65a9['savestate']==1)
 { if (!empty($this->logdata)) { if ($this->F4cca0efe()) continue; } } $this->V50dffd37= fopen($Vd6d33a32,"rb");
$Vad6e0d48=false; $this->V42dfa3a4['logfile_no']=$V7fa3b767; while(!feof($this->V50dffd37)) { $V6438c669 = fgets($this->V50dffd37, cBIG_STRING_LENGTH); 
 $V6438c669=rtrim($V6438c669,"\r\n"); if ($this->F20dd322a($V6438c669)==true) { $Vad6e0d48=true;
} } if ($this->V93da65a9['savestate']==1) { $this->F5c0b129c(); } fclose($this->V50dffd37); if ($Vad6e0d48)
 { } else { print "incomplete log: skipped\n"; } } } function Fe846ce3f($Vb0aae2e8) { foreach($this->Va2bbabfe as $V2bfe9d72 => $Vfde7a60d)
 { if (!strcmp($this->Va2bbabfe[$V2bfe9d72]['id'],$Vb0aae2e8)) { return $V2bfe9d72; } } return "";
} function Ffa84691e() { return date ("Y-m-d H:i:s", adodb_mktime ($this->V110decc3['hour'],$this->V110decc3['min'],$this->V110decc3['sec'],$this->V110decc3['month'],$this->V110decc3['date'],$this->V110decc3['year']));
} function F39068f61(&$V6438c669) { if (!preg_match("/^\"(.+)<(.+)><(.+)><(.*)>\" killed \"(.+)<(.+)><(.+)><(.*)>\"( with \"(.+)\")?/", $V6438c669, $Vb74df323))
 return false; $V7edf0aa1=$Vb74df323[1]; $V4b8cff0e=$Vb74df323[2]; $V193e9337=$Vb74df323[3]; $V0c0ebc3b=$Vb74df323[4];
 $V2da111cd=$Vb74df323[5]; $V6426a622=$Vb74df323[6]; $Vf1d77712=$Vb74df323[7]; $Vebab7890=$Vb74df323[8];
if (isset($Vb74df323[10])) $V2e7bf2ef=$Vb74df323[10]; else $V2e7bf2ef="Unknown"; if (!isset($this->Va2bbabfe[$V4b8cff0e]))
 { $V3edf73cd="\"$V7edf0aa1<$V4b8cff0e><$V193e9337><>\" entered the game"; $this->F46900171($V3edf73cd);
$V441c01bc = "\"$V7edf0aa1<$V4b8cff0e><$V193e9337><>\" joined team \"$V0c0ebc3b\""; $this->F8a700b43($V441c01bc);
} if (!isset($this->Va2bbabfe[$V6426a622])) { $V3edf73cd="\"$V2da111cd<$V6426a622><$Vf1d77712><>\" entered the game"; 
 $this->F46900171($V3edf73cd); $V441c01bc = "\"$V2da111cd<$V6426a622><$Vf1d77712><>\" joined team \"$Vebab7890\""; 
 $this->F8a700b43($V441c01bc); } $this->Vae2aeb93->Fd65f3244($this->Va2bbabfe[$V4b8cff0e]['id'],$this->Va2bbabfe[$V6426a622]['id'],$V2e7bf2ef);
 return true; } function Fcdf7bc3b(&$V6438c669) { if (!preg_match("/^\"(.+)<(.+)><(.+)><(.*)>\" committed suicide with \"(.+)\"/", $V6438c669, $Vb74df323))
 return false; $Vc1a5f989=$Vb74df323[1]; $V2bfe9d72=$Vb74df323[2]; $V0b5a0d9e=$Vb74df323[3]; $Vbd72949b=$Vb74df323[4];
$V2e7bf2ef=$Vb74df323[5]; if (!isset($this->Va2bbabfe[$V2bfe9d72])) { $V3edf73cd="\"$Vc1a5f989<$V2bfe9d72><$V0b5a0d9e><>\" entered the game"; 
 $this->F46900171($V3edf73cd); $V441c01bc = "\"$Vc1a5f989<$V2bfe9d72><$V0b5a0d9e><>\" joined team \"$Vbd72949b\""; 
 $this->F8a700b43($V441c01bc); } $this->Vae2aeb93->Fd65f3244($this->Va2bbabfe[$V2bfe9d72]['id'],$this->Va2bbabfe[$V2bfe9d72]['id'],$V2e7bf2ef);
return true; } function Fead7ba5b(&$V6438c669) { if (!preg_match("/^\"(.+)<(.+)><(.+)><(.*)>\" triggered \"(.*)\" against \"(.+)<(.+)><(.+)><(.*)>\" with \"(.*)\"$/", $V6438c669, $Vb74df323))
 if (!preg_match("/^\"(.+)<(.+)><(.+)><(.*)>\" triggered \"(.*)\" against \"(.+)<(.+)><(.+)><(.*)>\"$/", $V6438c669, $Vb74df323))
 return false; $Vc1a5f989=$Vb74df323[1]; $V2bfe9d72=$Vb74df323[2]; $V0b5a0d9e=$Vb74df323[3]; $Vbd72949b=$Vb74df323[4];
$V418c5509=$Vb74df323[5]; $V4bc8c720=$Vb74df323[6]; $Vbaa1129b=$Vb74df323[7]; $V2a6403c3=$Vb74df323[8];
$V5cdbd59b=$Vb74df323[9]; if (!isset($this->Va2bbabfe[$V2bfe9d72])||!isset($this->Va2bbabfe[$Vbaa1129b]))
 { $V3edf73cd="\"$Vc1a5f989<$V2bfe9d72><$V0b5a0d9e><>\" entered the game"; $this->F46900171($V3edf73cd);
$V441c01bc = "\"$Vc1a5f989<$V2bfe9d72><$V0b5a0d9e><>\" joined team \"$Vbd72949b\""; $this->F8a700b43($V441c01bc);
$V3edf73cd="\"$V4bc8c720<$Vbaa1129b><$V2a6403c3><>\" entered the game"; $this->F46900171($V3edf73cd);
$V441c01bc = "\"$V4bc8c720<$Vbaa1129b><$V2a6403c3><>\" joined team \"$V5cdbd59b\""; $this->F8a700b43($V441c01bc);
} if (isset($this->Va2bbabfe[$V2bfe9d72]['id']) && isset($this->Va2bbabfe[$Vbaa1129b]['id'])) { $this->Vae2aeb93->F4135e567($this->Va2bbabfe[$V2bfe9d72]['id'],$this->Va2bbabfe[$Vbaa1129b]['id'],'pvp|'.$V418c5509,1);
} return true; } function Fae0d89b2(&$V6438c669) { if (!preg_match("/^\"(.+)<(.+)><(.+)><(.*)>\" triggered \"(.*)\"$/", $V6438c669, $Vb74df323))
 return false; $Vc1a5f989=$Vb74df323[1]; $V2bfe9d72=$Vb74df323[2]; $V0b5a0d9e=$Vb74df323[3]; $Vbd72949b=$Vb74df323[4];
$V418c5509=$Vb74df323[5]; if (!isset($this->Va2bbabfe[$V2bfe9d72])) { $V3edf73cd="\"$Vc1a5f989<$V2bfe9d72><$V0b5a0d9e><>\" entered the game"; 
 $this->F46900171($V3edf73cd); $V441c01bc = "\"$Vc1a5f989<$V2bfe9d72><$V0b5a0d9e><>\" joined team \"$Vbd72949b\""; 
 $this->F8a700b43($V441c01bc); } if (isset($this->Va2bbabfe[$V2bfe9d72]['id'])) { $this->Vae2aeb93->F72d01d3f($this->Va2bbabfe[$V2bfe9d72]['id'],$V418c5509,1);
} return true; } function F017f6ac0(&$V6438c669) { if (!preg_match("/^\"(.+)<(.+)><(.+)><(.*)>\" triggered \"weaponstats\" \(weapon \"([^\"]*)\"\) \(shots \"([^\"]*)\"\) \(hits \"([^\"]*)\"\) .*\(damage \"([^\"]*)\"\)/", $V6438c669, $Vb74df323))
 return false; $V2bfe9d72=$Vb74df323[2]; $V47239253=$Vb74df323[5]; $V9f892c18=$Vb74df323[6]; $Vfce79135=$Vb74df323[7];
if (isset($this->Va2bbabfe[$V2bfe9d72]['id'])) { $this->Vae2aeb93->F4135e567($this->Va2bbabfe[$V2bfe9d72]['id'],$this->Va2bbabfe[$V2bfe9d72]['id'],"accuracy|{$V47239253}_hits",$Vfce79135);
$this->Vae2aeb93->F4135e567($this->Va2bbabfe[$V2bfe9d72]['id'],$this->Va2bbabfe[$V2bfe9d72]['id'],"accuracy|{$V47239253}_shots",$V9f892c18);
} return true; } function F6ec40ba4(&$V6438c669) { if (!preg_match("/^\"(.+)<(.+)><(.+)><(.*)>\" triggered \"weaponstats2\" \(weapon \"([^\"]*)\"\) \(head \"([^\"]*)\"\) \(chest \"([^\"]*)\"\) .*\(stomach \"([^\"]*)\"\) .*\(leftarm \"([^\"]*)\"\) .*\(rightarm \"([^\"]*)\"\) .*\(leftleg \"([^\"]*)\"\) .*\(rightleg \"([^\"]*)\"\)/", $V6438c669, $Vb74df323))
 return false; $V2bfe9d72=$Vb74df323[2]; $V47239253=$Vb74df323[5]; $Vf803abdc=$Vb74df323[6]; $V825c3118=$Vb74df323[7];
$Vf0033454=$Vb74df323[8]; $V3631b121=$Vb74df323[9]; $V58add1e4=$Vb74df323[10]; $V75d50a08=$Vb74df323[11];
$V28d0e16f=$Vb74df323[12]; if (isset($this->Va2bbabfe[$V2bfe9d72]['id'])) { $this->Vae2aeb93->F4135e567($this->Va2bbabfe[$V2bfe9d72]['id'],$this->Va2bbabfe[$V2bfe9d72]['id'],"accuracy|{$V47239253}_lochead",$Vf803abdc);
$this->Vae2aeb93->F4135e567($this->Va2bbabfe[$V2bfe9d72]['id'],$this->Va2bbabfe[$V2bfe9d72]['id'],"accuracy|{$V47239253}_locchest",$V825c3118);
$this->Vae2aeb93->F4135e567($this->Va2bbabfe[$V2bfe9d72]['id'],$this->Va2bbabfe[$V2bfe9d72]['id'],"accuracy|{$V47239253}_locstomach",$Vf0033454);
$this->Vae2aeb93->F4135e567($this->Va2bbabfe[$V2bfe9d72]['id'],$this->Va2bbabfe[$V2bfe9d72]['id'],"accuracy|{$V47239253}_locarm-left",$V3631b121);
$this->Vae2aeb93->F4135e567($this->Va2bbabfe[$V2bfe9d72]['id'],$this->Va2bbabfe[$V2bfe9d72]['id'],"accuracy|{$V47239253}_locarm-right",$V58add1e4);
$this->Vae2aeb93->F4135e567($this->Va2bbabfe[$V2bfe9d72]['id'],$this->Va2bbabfe[$V2bfe9d72]['id'],"accuracy|{$V47239253}_locleg-left",$V75d50a08);
$this->Vae2aeb93->F4135e567($this->Va2bbabfe[$V2bfe9d72]['id'],$this->Va2bbabfe[$V2bfe9d72]['id'],"accuracy|{$V47239253}_locleg-right",$V28d0e16f);
} return true; } function F546b522d(&$V6438c669) { if (!preg_match("/^\"(.+)<(.+)><(.+)><(.*)>\" attacked \"(.+)<(.+)><(.+)><(.*)>\" with \"(.*)\"/", $V6438c669, $Vb74df323))
 return false; $V4b8cff0e=$Vb74df323[2]; $V6426a622=$Vb74df323[6]; $V2e7bf2ef=$Vb74df323[9]; $this->Vae2aeb93->F4135e567($this->Va2bbabfe[$V4b8cff0e]['id'],$this->Va2bbabfe[$V6426a622]['id'],"hits|{$V2e7bf2ef}",1);
return true; } function F3237fc51(&$V6438c669) { if (!preg_match("/^\"(.+)<(.+)><(.+)><(.*)>\" say \"(.*)\"/", $V6438c669, $Vb74df323))
 return false; $V2bfe9d72=$Vb74df323[2]; $Vaa8af3eb=$Vb74df323[5]; $this->Vae2aeb93->F8405e6ea($this->Va2bbabfe[$V2bfe9d72]['id'],$Vaa8af3eb); 
 return true; } function F07a4d494($Va97612a0) { foreach($this->Va2bbabfe as $V74aaef3b => $V9ba96d33)
 { if (!strcmp($this->Va2bbabfe[$V74aaef3b]['guid'],$Va97612a0)) { return $V74aaef3b; } } return "";
} function Facd26164($Va97612a0) { $V2bfe9d72=""; $Vfb2d949e=ftell($this->V50dffd37); while(!feof($this->V50dffd37))
 { $Vb16ebe0a = fgets($this->V50dffd37, cBIG_STRING_LENGTH); $Vb16ebe0a = rtrim($Vb16ebe0a,"\r\n"); 
 if (preg_match("/<(\d+)><$Va97612a0>/",$Vb16ebe0a,$Vb74df323)) { $V2bfe9d72=$Vb74df323[1]; break;
} } fseek($this->V50dffd37,$Vfb2d949e); return $V2bfe9d72; } function Fac7525e6(&$V6438c669) { if (!preg_match("/^\"(.+)<(.+)><(.*)>\" joined team \"(.*)\"/", $V6438c669, $Vb74df323))
 return false; $Vc1a5f989=$Vb74df323[1]; $V0b5a0d9e=$Vb74df323[2]; $Vfa69cfb9=$Vb74df323[3]; $Vbd72949b=$Vb74df323[4]; 
 $V2bfe9d72=$this->F07a4d494($V0b5a0d9e); if (strlen($V2bfe9d72)<=0) { $V2bfe9d72=$this->Facd26164($V0b5a0d9e);
if (strlen($V2bfe9d72)<=0) { echo "problem: could not find a client id in\n"; echo "$V6438c669\n";
return true; } $V3edf73cd="\"$Vc1a5f989<$V2bfe9d72><$V0b5a0d9e><>\" entered the game"; $this->F46900171($V3edf73cd);
} $V441c01bc = "\"$Vc1a5f989<$V2bfe9d72><$V0b5a0d9e><$Vfa69cfb9>\" joined team \"$Vbd72949b\""; $this->F8a700b43($V441c01bc);
 return true; } function F8a700b43(&$V6438c669) { if (!preg_match("/^\"(.+)<(.+)><(.+)><(.*)>\" joined team \"(.*)\"/", $V6438c669, $Vb74df323))
 return false; $Vc1a5f989=$Vb74df323[1]; $V2bfe9d72=$Vb74df323[2]; $V0b5a0d9e=$Vb74df323[3]; $Vbd72949b=$Vb74df323[5]; 
 if ($Vbd72949b=="SPECTATOR" || $Vbd72949b=="Unassigned") return true; $this->Vae2aeb93->F555c9055($this->Va2bbabfe[$V2bfe9d72]['id'],$Vbd72949b);
return true; } function F0a59b660(&$V6438c669) { if (!preg_match("/^\"(.+)<(.+)><(.+)><(.*)>\" disconnected/", $V6438c669, $Vb74df323))
 return false; return true; } function F18605c46(&$V6438c669) { if (!preg_match("/^\"(.+)<(.+)><(.+)><(.*)>\" changed name to \"(.+)\"/", $V6438c669, $Vb74df323))
 return false; $V2bfe9d72=$Vb74df323[2]; $V10b04069=$Vb74df323[5]; $this->Vae2aeb93->Fec5ab55c("sto",$this->Va2bbabfe[$V2bfe9d72]['id'],"alias",$V10b04069);
$this->Vae2aeb93->Fddcbd60f($this->Va2bbabfe[$V2bfe9d72]['id'],$V10b04069); if ($this->V93da65a9['trackID'] == 'playerName')
 { $this->Vae2aeb93->F95791962($this->Va2bbabfe[$V2bfe9d72]['id'],$V10b04069); $this->Va2bbabfe[$V2bfe9d72]['id']=$V10b04069;
} $this->Va2bbabfe[$V2bfe9d72]['name']=$V10b04069; return true; } function F46900171(&$V6438c669)
 { if (!preg_match("/^\"(.+)<([^>]+)><([^>]+)>.*\" entered the game/", $V6438c669, $Vb74df323)) return false;
$Vc1a5f989=$Vb74df323[1]; $V2bfe9d72=$Vb74df323[2]; $V0b5a0d9e=$Vb74df323[3]; if (isset($this->Va2bbabfe[$V2bfe9d72]))
 { return true; } $this->Va2bbabfe[$V2bfe9d72]['guid']=$V0b5a0d9e; if (isset($this->V6d2b5d2c['ip'][$V2bfe9d72]))
 $this->Va2bbabfe[$V2bfe9d72]['ip']=$this->V6d2b5d2c['ip'][$V2bfe9d72]; if ($this->V93da65a9['trackID'] == 'playerName')
 { $this->Va2bbabfe[$V2bfe9d72]['id']=$Vc1a5f989; } else if ($this->V93da65a9['trackID'] == 'guid' && isset($this->Va2bbabfe[$V2bfe9d72]['guid']))
 { $this->Va2bbabfe[$V2bfe9d72]['id']=$this->Va2bbabfe[$V2bfe9d72]['guid']; } else if (preg_match("/^ip=(.+)/i",$this->V93da65a9['trackID'],$Vd6fd0924) 
 && isset($this->Va2bbabfe[$V2bfe9d72]['ip']) && preg_match($Vd6fd0924[1],$this->Va2bbabfe[$V2bfe9d72]['ip'],$V793914c9))
 { $this->Va2bbabfe[$V2bfe9d72]['id']=$V793914c9[1]; } else { Fb7d30ee1("\$cfg['parser']['trackID'] is invalid, ignored\n");
Fb7d30ee1("Use \$cfg['parser']['trackID'] = 'playerName'; in your config\n"); Fb7d30ee1("{$this->Vc3ecd549} $V6438c669\n");
$this->Vae2aeb93->F242ca9da(); $this->Vdafa753c= false; return true; } $this->Va2bbabfe[$V2bfe9d72]['name']=$Vc1a5f989; 
 if (isset($this->Va2bbabfe[$V2bfe9d72]['id'])) { $this->Vae2aeb93->F6aae4907($this->Va2bbabfe[$V2bfe9d72]['id'],$this->Va2bbabfe[$V2bfe9d72]['name']); 
 if (isset($this->Va2bbabfe[$V2bfe9d72]['ip'])) $this->Vae2aeb93->Fec5ab55c("sto",$this->Va2bbabfe[$V2bfe9d72]['id'],"ip",$this->Va2bbabfe[$V2bfe9d72]['ip']);
if (isset($this->Va2bbabfe[$V2bfe9d72]['guid'])) $this->Vae2aeb93->Fec5ab55c("sto",$this->Va2bbabfe[$V2bfe9d72]['id'],"guid",$this->Va2bbabfe[$V2bfe9d72]['guid']);
} return true; } function F6e2de63f(&$V6438c669) { if (!preg_match("/^\"(.+)<([^>]+)>.*\" connected, address \"([0-9\\.]+):\d+\"/", $V6438c669, $Vb74df323))
 return false; $this->V6d2b5d2c['ip'][$Vb74df323[2]]=$Vb74df323[3]; return true; } function F027cb40c(&$V6438c669)
 { if (!preg_match("/^World triggered \"Match_Begins_Now\"/", $V6438c669)) return false; $this->Vae2aeb93->Fb03ee647();
return true; } function F9a8d7c2f(&$V6438c669) { if (!preg_match("/^Log file started \\(file \"(.*)\"\\) \\(game \"(.*)\"\\) \\(version \"(.*)\"\\)/", $V6438c669, $Vb74df323))
 return false; $this->Vdafa753c= true; $Ve37f0136['mod']=$Vb74df323[2]; if (preg_match("/([^\\/\\\\]+)$/",$Ve37f0136['mod'],$Va9ddcf51))
 { $Ve37f0136['mod']=$Va9ddcf51[1]; } $Ve37f0136['version']=$Vb74df323[3]; $this->Vae2aeb93->Fd45b6912();
$this->Vae2aeb93->F6d04475a("_v_game",'hl'); $this->Vae2aeb93->F6d04475a("_v_time_start",$this->Ffa84691e());
$this->Vae2aeb93->F6d04475a("_v_mod",$Ve37f0136['mod']); $this->Vae2aeb93->F6d04475a("_v_game_type",$Ve37f0136['mod']);
$this->Vae2aeb93->F6d04475a("version",$Ve37f0136['version']); return true; } function F1d8f6b73(&$V6438c669)
 { if (!preg_match("/^Log.* closed/", $V6438c669, $Vb74df323)) return false; if (isset($this->V6d2b5d2c['team_score']))
 { arsort($this->V6d2b5d2c['team_score']); $V89565361=key($this->V6d2b5d2c['team_score']); $this->Vae2aeb93->F89da123b($V89565361,"team|score",$this->V6d2b5d2c['team_score'][$V89565361]);
$this->Vae2aeb93->F89da123b($V89565361,"team|wins",1); unset($this->V6d2b5d2c['team_score'][$V89565361]);
 foreach($this->V6d2b5d2c['team_score'] as $V3dc5773b=>$Vecafcf8d) { $this->Vae2aeb93->F89da123b($V3dc5773b,"team|score",$this->V6d2b5d2c['team_score'][$V3dc5773b]);
$this->Vae2aeb93->F89da123b($V3dc5773b,"team|loss",1); } } $this->Vae2aeb93->Fc3b570a7(); $this->V21d8a920->F43781db5($this->Vae2aeb93->F26dd5333(),$this->Vae2aeb93->F068fac4f());
$this->Vae2aeb93->F242ca9da(); $this->Vdafa753c= false; return true; } function Ff3727ecb(&$V6438c669)
 { if (!preg_match("/^Loading map \"(.*)\"/", $V6438c669, $Vb74df323)) if (!preg_match("/^Started map \"(.*)\"/U", $V6438c669, $Vb74df323))
 return false; $this->Vae2aeb93->F6d04475a("_v_map",$Vb74df323[1]); return true; } function F13f1bede(&$V6438c669)
 { if (!preg_match("/^\"(.+)<(.+)><(.+)><(.*)>\" changed role to \"(.+)\"/", $V6438c669, $Vb74df323))
 return false; $V2bfe9d72=$Vb74df323[2]; $Vb55907a2=$Vb74df323[5]; $this->Vae2aeb93->Fa3f3cadc($this->Va2bbabfe[$V2bfe9d72]['id'],$Vb55907a2);
$this->Vae2aeb93->F72d01d3f($this->Va2bbabfe[$V2bfe9d72]['id'],"icon|$Vb55907a2",1); return true; } 
 function F26e40035(&$V6438c669) { if (!preg_match("/^Team \"(.*)\" scored \"(.*)\"/U", $V6438c669, $Vb74df323))
 return false; $Vf894427c=$Vb74df323[1]; $Vca1cd3c3=$Vb74df323[2]; $this->V6d2b5d2c['team_score'][$Vf894427c]=$Vca1cd3c3;
 return true; } function F26a565c8(&$V6438c669) { return false; } function F1ef9b71a(&$V6438c669)
 { if (!preg_match("/^L *(\d\d)\/(\d\d)\/(\d\d\d\d) - (\d\d):(\d\d):(\d\d): /", $V6438c669, $Vb74df323))
 return false; $this->V110decc3['month']=$Vb74df323[1]; $this->V110decc3['date']=$Vb74df323[2]; $this->V110decc3['year']=$Vb74df323[3];
$this->V110decc3['hour']=$Vb74df323[4]; $this->V110decc3['min']=$Vb74df323[5]; $this->V110decc3['sec']=$Vb74df323[6]; 
 $V6438c669=substr($V6438c669,strlen($Vb74df323[0])); return true; } function F20dd322a(&$V6438c669)
 { $this->F1ef9b71a($V6438c669); if ($this->F9a8d7c2f($V6438c669)) { echo sprintf("(%05.2f%%) ",100.0 * $this->V42dfa3a4['logfile_no']/$this->V42dfa3a4['logfile_total']);
} else if ($this->Vdafa753c) { if ($this->F26a565c8($V6438c669)) { } else if ($this->Ff3727ecb($V6438c669))
 { } else if ($this->F1d8f6b73($V6438c669)) { return true; } else if ($this->F39068f61($V6438c669))
 { } else if ($this->F6e2de63f($V6438c669)) { } else if ($this->F0a59b660($V6438c669)) { } else if ($this->F46900171($V6438c669))
 { } else if ($this->F8a700b43($V6438c669)) { } else if ($this->Fac7525e6($V6438c669)) { } else if ($this->F3237fc51($V6438c669))
 { } else if ($this->Fead7ba5b($V6438c669)) { } else if ($this->Fae0d89b2($V6438c669)) { } else if ($this->F017f6ac0($V6438c669))
 { } else if ($this->F6ec40ba4($V6438c669)) { } else if ($this->Fcdf7bc3b($V6438c669)) { } else if ($this->F546b522d($V6438c669))
 { } else if ($this->F18605c46($V6438c669)) { } else if ($this->F13f1bede($V6438c669)) { } else if ($this->F26e40035($V6438c669))
 { } else if ($this->F027cb40c($V6438c669)) { } else { } } else { } return false; } 
} ?>